# Nama workflow yang akan muncul di tab Actions
name: Deploy Website with GA ID

# Pemicu workflow
on:
  # Memungkinkan workflow ini dijalankan secara manual dari tab Actions
  workflow_dispatch:
    inputs:
      site_url:
        description: 'URL Lengkap Website yang akan dideploy'
        required: true
        # Nilai default ini sudah sesuai dengan URL Anda
        default: 'https://alyazzr.github.io/ujicoba/' 

# Pekerjaan yang akan dilakukan
jobs:
  deploy:
    runs-on: ubuntu-latest # Menjalankan di server virtual Linux

    steps:
      # Langkah 1: Mengambil kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Langkah 3: Instal library yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary pandas

      # Langkah 4: Ambil Measurement ID dari Database
      - name: Fetch Measurement ID from Database
        id: fetch_id 
        env:
          # BAGIAN INI MENGAMBIL DATA ANDA DARI "RAHASIA" REPOSITORI
          # Jadi, tidak ada password atau username yang ditulis di sini.
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          SITE_URL: ${{ github.event.inputs.site_url }}
        run: |
          import os
          import psycopg2
          import pandas as pd
          
          conn = psycopg2.connect(
              host=os.getenv('DB_HOST'),
              port=os.getenv('DB_PORT'),
              dbname=os.getenv('DB_NAME'),
              user=os.getenv('DB_USER'),
              password=os.getenv('DB_PASS')
          )
          query = f"SELECT ga_measurement_id FROM websites WHERE site_url = '{os.getenv('SITE_URL')}'"
          df = pd.read_sql_query(query, conn)
          conn.close()
          
          # Cek jika data ditemukan sebelum mencoba mengambilnya
          if df.empty:
            print(f"Error: Tidak ada data ditemukan di database untuk URL {os.getenv('SITE_URL')}")
            exit(1)
          
          measurement_id = df['ga_measurement_id'][0]
          print(f"Measurement ID found: {measurement_id}")
          
          # Menyimpan ID sebagai output dari langkah ini
          echo "ga_id=${measurement_id}" >> $GITHUB_OUTPUT

      # Langkah 5: Ganti Placeholder di file index.html
      - name: Replace Placeholder in HTML
        run: |
          GA_ID="${{ steps.fetch_id.outputs.ga_id }}"
          # Perintah 'sed' ini akan mencari dan mengganti placeholder
          sed -i "s|__GA_MEASUREMENT_ID__|${GA_ID}|g" index.html
          echo "Placeholder replaced in index.html"

      # Langkah 6: Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
